/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectopolilacolonia2.CategoriaDeporte;
import proyectopolilacolonia2.Deporte;

/**
 *
 * @author Pablo2
 */
public class Registro_Deportes_Categorias extends javax.swing.JFrame {

    private ResultSet rs = null;
    
    public Registro_Deportes_Categorias() {
        initComponents();
        this.llenarDeporteCBox();
        this.mostrarCategorias();
    }

    private void mostrarCategorias() {
        rs = new CategoriaDeporte().tableView1();
        DefaultTableModel modelo = (DefaultTableModel) this.categoriasDeportesJTable.getModel();
        modelo.setRowCount(0);
        int columnas = modelo.getColumnCount();
        
        try {
            while(rs.next()) {
                Object fila[] = new Object[columnas];
                for(int i=0; i < fila.length; i++) {
                    fila[i] = rs.getObject(i+1);
                }
                modelo.addRow(fila);
                
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void llenarDeporteCBox() {
        rs = new Deporte().list();
        
        this.deportesCBox.removeAllItems();
        
        try {
            while(rs.next()) {
                this.deportesCBox.addItem(rs.getString("nombre"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombreDeporteTxtField = new javax.swing.JTextField();
        registrarDeporteTxtField = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        deportesCBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        nombreCategoriaTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        valorCuotaTxtField = new javax.swing.JTextField();
        registrarCategoriaBtn = new javax.swing.JButton();
        editarCategoriaBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoriasDeportesJTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(56, 142, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DEPORTES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jLabel1.setText("Nombre del deporte:");

        registrarDeporteTxtField.setText("Registrar deporte");
        registrarDeporteTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarDeporteTxtFieldActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(56, 142, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CATEGORÍAS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jLabel2.setText("Listado de deportes:");

        deportesCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", " " }));

        jLabel3.setText("Nombre de la categoría:");

        jLabel4.setText("Valor de la cuota:");

        registrarCategoriaBtn.setText("Registrar categoría");
        registrarCategoriaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarCategoriaBtnActionPerformed(evt);
            }
        });

        editarCategoriaBtn.setText("Modificar categoría");
        editarCategoriaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCategoriaBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Listado de categorias de deportes:");

        categoriasDeportesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Deporte ", "Categoría", "Valor de la cuota"
            }
        ));
        categoriasDeportesJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriasDeportesJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(categoriasDeportesJTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrarCategoriaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarDeporteTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nombreDeporteTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addComponent(editarCategoriaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deportesCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreCategoriaTxtField)
                            .addComponent(valorCuotaTxtField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreDeporteTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarDeporteTxtField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(deportesCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombreCategoriaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(valorCuotaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarCategoriaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarCategoriaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarDeporteTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarDeporteTxtFieldActionPerformed
        if(this.nombreDeporteTxtField.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "¡Este campo no puede estar vacio!", "Error: campo vacio.", JOptionPane.ERROR_MESSAGE);
        } else {
            String nombreDeporte = this.nombreDeporteTxtField.getText().trim();
            Deporte deporte = new Deporte();
            deporte.setNombre(nombreDeporte);
            deporte.save(deporte);
            
            this.llenarDeporteCBox();
            
        }
    }//GEN-LAST:event_registrarDeporteTxtFieldActionPerformed

    private void registrarCategoriaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCategoriaBtnActionPerformed
        if(this.nombreCategoriaTxtField.getText().trim().equalsIgnoreCase("") || this.valorCuotaTxtField.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "¡Los campos no pueden estar vacios!", "Error: campo vacio.", JOptionPane.ERROR_MESSAGE);
        } else {
            
            String nombreCategoria = this.nombreCategoriaTxtField.getText().trim();
            Double valorCuota = Double.valueOf(this.valorCuotaTxtField.getText().trim());
            String nombreDeporte = this.deportesCBox.getSelectedItem().toString();
            
            Deporte deporte = new Deporte().findByName(nombreDeporte);
            
            CategoriaDeporte categoria = new CategoriaDeporte();
            categoria.setNombre(nombreCategoria);
            categoria.setDeporteId(deporte.getId());
            categoria.setValorCuota(valorCuota);
            categoria.save(categoria);
            
            this.mostrarCategorias();
            
        }
    }//GEN-LAST:event_registrarCategoriaBtnActionPerformed

    private void editarCategoriaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCategoriaBtnActionPerformed
        if(this.nombreCategoriaTxtField.getText().trim().equalsIgnoreCase("") || this.valorCuotaTxtField.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "¡Los campos no pueden estar vacios!", "Error: campo vacio.", JOptionPane.ERROR_MESSAGE);
        } else {
            
            String nombreCategoria = this.nombreCategoriaTxtField.getText().trim();
            Double valorCuota = Double.valueOf(this.valorCuotaTxtField.getText().trim());
            int fila = this.categoriasDeportesJTable.getSelectedRow();
            int categoriaId = Integer.valueOf(this.categoriasDeportesJTable.getValueAt(fila, 0).toString());
          
            CategoriaDeporte categoria = new CategoriaDeporte();
            categoria.setNombre(nombreCategoria);
            categoria.setValorCuota(valorCuota);
            categoria.setId(categoriaId);
            categoria.update(categoria);
            
            
            this.mostrarCategorias();
            
        }
    }//GEN-LAST:event_editarCategoriaBtnActionPerformed

    private void categoriasDeportesJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriasDeportesJTableMouseClicked
        int fila = this.categoriasDeportesJTable.getSelectedRow();
        String nombreDeporte = this.categoriasDeportesJTable.getValueAt(fila, 1).toString();
        String nombreCategoria = this.categoriasDeportesJTable.getValueAt(fila, 2).toString();
        String valorCuota = this.categoriasDeportesJTable.getValueAt(fila, 3).toString();
        
        this.nombreCategoriaTxtField.setText(nombreCategoria);
        this.valorCuotaTxtField.setText(valorCuota);
        
        for(int i=0; i < deportesCBox.getItemCount(); i++) {
            if(deportesCBox.getItemAt(i).toString().equalsIgnoreCase(nombreDeporte)) {
                deportesCBox.setSelectedIndex(i);
            }
        }
    }//GEN-LAST:event_categoriasDeportesJTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Deportes_Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Deportes_Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Deportes_Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Deportes_Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Deportes_Categorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable categoriasDeportesJTable;
    private javax.swing.JComboBox<String> deportesCBox;
    private javax.swing.JButton editarCategoriaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombreCategoriaTxtField;
    private javax.swing.JTextField nombreDeporteTxtField;
    private javax.swing.JButton registrarCategoriaBtn;
    private javax.swing.JButton registrarDeporteTxtField;
    private javax.swing.JTextField valorCuotaTxtField;
    // End of variables declaration//GEN-END:variables
}
