/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectopolilacolonia2.Alumno;
import proyectopolilacolonia2.Profesor;

/**
 *
 * @author Pablo2
 */
public class Registro_Personas extends javax.swing.JFrame {

    private ResultSet rs = null;
    
    public Registro_Personas() {
        initComponents();
        
        sexoGroupBtn.add(masculinoRBtn);
        sexoGroupBtn.add(femeninoRBtn);
        sexoGroupBtn.add(otroRBtn);
        
        anoCBox.removeAllItems();
        
        for(int i=1900; i < 2100; i++) {
            anoCBox.addItem(String.valueOf(i));
        }
        
        this.mostrarAlumnos();
        
    }
    
    private void mostrarProfesores() {
        DefaultTableModel modelo = (DefaultTableModel) this.personasJTable.getModel();
        int columnas = modelo.getColumnCount();
        modelo.setRowCount(0);
        
        rs = new Profesor().list();
        
        try {
            while(rs.next()) {
                Object fila[] = new Object[columnas];
                
                fila[0] = rs.getObject("id");
                fila[1] = rs.getObject("dni");
                fila[2] = rs.getObject("codTarjeta");
                fila[3] = rs.getObject("nombreCompleto");
                fila[4] = rs.getObject("telefono");
                fila[5] = rs.getObject("sexo");
                fila[6] = rs.getObject("fechaNacimiento");
                fila[7] = rs.getObject("created_at");
                
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void mostrarAdministrativos() {
        
    }
    
    private void mostrarAlumnos() {
        DefaultTableModel modelo = (DefaultTableModel) this.personasJTable.getModel();
        modelo.setRowCount(0);
        
        
        rs = new Alumno().list();
        
        int columnas = modelo.getColumnCount();
        
        try {
            while(rs.next()) {
                Object fila[] = new Object[columnas];
                
                fila[0] = rs.getObject("id");
                fila[1] = rs.getObject("dni");
                fila[2] = rs.getObject("codTarjeta");
                fila[3] = rs.getObject("nombreCompleto");
                fila[4] = rs.getObject("telefono");
                fila[5] = rs.getObject("sexo");
                fila[6] = rs.getObject("fechaNacimiento");
                fila[7] = rs.getObject("created_at");
                
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoGroupBtn = new javax.swing.ButtonGroup();
        personasPopUpMenu = new javax.swing.JPopupMenu();
        eliminarItem = new javax.swing.JMenuItem();
        editarItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tipoCBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        nombreTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dniTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        codTarjetaTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mesCBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        telefonoTxtField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        masculinoRBtn = new javax.swing.JRadioButton();
        femeninoRBtn = new javax.swing.JRadioButton();
        otroRBtn = new javax.swing.JRadioButton();
        registrarBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        buscarDniTxtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        personasJTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        diaCBox = new javax.swing.JComboBox<>();
        anoCBox = new javax.swing.JComboBox<>();

        eliminarItem.setText("Eliminar...");
        personasPopUpMenu.add(eliminarItem);

        editarItem.setText("Editar...");
        personasPopUpMenu.add(editarItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(56, 142, 60));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("REGISTRO DE USUARIOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel1.setText("Tipo de usuario:");

        tipoCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Profesor", "Administrativo" }));
        tipoCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre y apellido:");

        jLabel3.setText("DNI:");

        jLabel4.setText("Codigo de tarjeta:");

        jLabel5.setText("Fecha de nacimiento:");

        jLabel6.setText("Día:");

        jLabel7.setText("Mes:");

        mesCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel8.setText("Año:");

        jLabel9.setText("Teléfono:");

        jLabel10.setText("Sexo:");

        masculinoRBtn.setSelected(true);
        masculinoRBtn.setText("Masculino");

        femeninoRBtn.setText("Femenino");

        otroRBtn.setText("Otro");

        registrarBtn.setText("Registrar");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("DNI:");

        personasJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "DNI", "Nº tarjeta", "Nombre y apellido", "Género", "Teléfono", "Fecha de nacimiento", "Fecha de registro"
            }
        ));
        personasJTable.setComponentPopupMenu(personasPopUpMenu);
        jScrollPane1.setViewportView(personasJTable);

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        diaCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        anoCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diaCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mesCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(anoCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(masculinoRBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(femeninoRBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(otroRBtn)
                                .addGap(192, 192, 192))
                            .addComponent(telefonoTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarDniTxtField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codTarjetaTxtField)
                            .addComponent(tipoCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreTxtField)
                            .addComponent(dniTxtField))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipoCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dniTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(codTarjetaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(mesCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(diaCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(telefonoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(masculinoRBtn)
                    .addComponent(femeninoRBtn)
                    .addComponent(otroRBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registrarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(buscarDniTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        
        if(nombreTxtField.getText().trim().equalsIgnoreCase("") || dniTxtField.getText().trim().equalsIgnoreCase("") || codTarjetaTxtField.getText().trim().equalsIgnoreCase("") || telefonoTxtField.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "¡Ningún campo puede quedar vacio!", "Error: campos vacios.", JOptionPane.ERROR_MESSAGE);
        } else {
            
            String nombreCompleto = nombreTxtField.getText().trim();
            String dni = dniTxtField.getText().trim();
            String codTarjeta = codTarjetaTxtField.getText().trim();
            String telefono = telefonoTxtField.getText().trim();
            String sexo = "";
            int dia, ano, mesNum = 0;
            String mes;
            LocalDate fechaNacimiento;
            
            if(masculinoRBtn.isSelected()) {
                sexo = "masculino";
            } else {
                if(femeninoRBtn.isSelected()) {
                    sexo = "femenino";
                } else {
                    sexo = "otro";
                }
            }
            
            dia = Integer.valueOf(diaCBox.getSelectedItem().toString());
            ano = Integer.valueOf(anoCBox.getSelectedItem().toString());
            
            mes = mesCBox.getSelectedItem().toString();
            
            switch(mes) {
                case "Enero": mesNum = 1;
                break;
                case "Febrero": mesNum = 2;
                break;
                case "Marzo": mesNum = 3;
                break;
                case "Abril": mesNum = 4;
                break;
                case "Mayo": mesNum = 5;
                break;
                case "Junio": mesNum = 6;
                break;
                case "Julio": mesNum = 7;
                break;
                case "Agosto": mesNum = 8;
                break;
                case "Septiembre": mesNum = 9;
                break;
                case "Octubre": mesNum = 10;
                break;
                case "Noviembre": mesNum = 11;
                break;
                case "Diciembre": mesNum = 12;
                    
            }
            
            fechaNacimiento = LocalDate.of(ano, mesNum, dia);
            
            if(this.tipoCBox.getSelectedItem().toString().equalsIgnoreCase("alumno")) {
                Alumno alumno = new Alumno();
                alumno.setNombreCompleto(nombreCompleto);
                alumno.setCodTarjeta(codTarjeta);
                alumno.setSexo(sexo);
                alumno.setTelefono(telefono);
                alumno.setDni(dni);
                alumno.setCreated_at(LocalDateTime.now());
                alumno.setFechaNacimiento(fechaNacimiento);
                alumno.setTipo("alumno");
                alumno.save(alumno);
                
            } else {
                if(this.tipoCBox.getSelectedItem().toString().equalsIgnoreCase("profesor")) {
                    Profesor profesor = new Profesor();
                    profesor.setNombreCompleto(nombreCompleto);
                    profesor.setCodTarjeta(codTarjeta);
                    profesor.setSexo(sexo);
                    profesor.setTelefono(telefono);
                    profesor.setDni(dni);
                    profesor.setCreated_at(LocalDateTime.now());
                    profesor.setFechaNacimiento(fechaNacimiento);
                    profesor.setTipo("profesor");
                    profesor.save(profesor);
                }
            }
            
        }
        
    }//GEN-LAST:event_registrarBtnActionPerformed

    private void tipoCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCBoxActionPerformed
        String tipo = this.tipoCBox.getSelectedItem().toString();
        
        if(tipo.equalsIgnoreCase("alumno")) {
            mostrarAlumnos();
        } else {
            if(tipo.equalsIgnoreCase("profesor")) {
                mostrarProfesores();
            } else {
                mostrarAdministrativos();
            }
            
        }
    }//GEN-LAST:event_tipoCBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String dni = buscarDniTxtField.getText().trim();
        
        if(dni.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "¡Ingrese un DNI para buscar!" , "Error: campo vacio.", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) personasJTable.getModel();
        
            for(int i=0; i < modelo.getRowCount(); i++) {
                if(dni.equalsIgnoreCase(modelo.getValueAt(i, 1).toString())) {
                    personasJTable.setRowSelectionInterval(i, i);
                }
            }
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Personas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Personas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> anoCBox;
    private javax.swing.JTextField buscarDniTxtField;
    private javax.swing.JTextField codTarjetaTxtField;
    private javax.swing.JComboBox<String> diaCBox;
    private javax.swing.JTextField dniTxtField;
    private javax.swing.JMenuItem editarItem;
    private javax.swing.JMenuItem eliminarItem;
    private javax.swing.JRadioButton femeninoRBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton masculinoRBtn;
    private javax.swing.JComboBox<String> mesCBox;
    private javax.swing.JTextField nombreTxtField;
    private javax.swing.JRadioButton otroRBtn;
    private javax.swing.JTable personasJTable;
    private javax.swing.JPopupMenu personasPopUpMenu;
    private javax.swing.JButton registrarBtn;
    private javax.swing.ButtonGroup sexoGroupBtn;
    private javax.swing.JTextField telefonoTxtField;
    private javax.swing.JComboBox<String> tipoCBox;
    // End of variables declaration//GEN-END:variables
}
