/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectopolilacolonia2.Alumno;
import proyectopolilacolonia2.Contacto;

/**
 *
 * @author Pablo2
 */
public class Registro_Contactos extends javax.swing.JFrame {

    private ResultSet rs = null;
    
    
    public Registro_Contactos() {
        initComponents();
    }
    
    private void mostrarAlumnos() {
        
        rs = new Alumno().list();
        
        DefaultTableModel modelo = (DefaultTableModel) this.personasJTable.getModel();
        modelo.setRowCount(0);
        int columnas = modelo.getColumnCount();
        
        try {
            while(rs.next()) {
                Object fila[] = new Object[columnas];
                
                fila[0] = rs.getObject("id");
                fila[1] = rs.getObject("dni");
                fila[2] = rs.getObject("nombreCompleto");
                
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    private void mostrarProfesores() {
        
    }
    
    private void mostrarAdministrativos() {
        
    }
    
    private void mostrarContactos() {
        int filaSeleccionada = this.personasJTable.getSelectedRow();
        int personaId = Integer.valueOf(this.personasJTable.getValueAt(filaSeleccionada, 0).toString());
        
        DefaultTableModel modelo = (DefaultTableModel) this.contactosJTable.getModel();
        modelo.setRowCount(0);
        int columnas = modelo.getColumnCount();
        
        rs = new Contacto().list(personaId);
        try {
            while(rs.next()) {
                Object fila[] = new Object[columnas];
                
                fila[0] = rs.getObject("id");
                fila[1] = rs.getObject("nombre");
                fila[2] = rs.getObject("telefono");
                fila[3] = rs.getObject("relacion");
                
                modelo.addRow(fila);
                
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactosPopUp = new javax.swing.JPopupMenu();
        eliminarItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipoCBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        buscarDniTxtField = new javax.swing.JTextField();
        buscarDniBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        personasJTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        nombreContactoTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefonoTxtField = new javax.swing.JTextField();
        registrarBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        contactosJTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        relacionCBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        personaSeleccionadaTxtField = new javax.swing.JTextField();

        eliminarItem.setText("Eliminar...");
        eliminarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarItemActionPerformed(evt);
            }
        });
        contactosPopUp.add(eliminarItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jLabel1.setText("Tipo de usuario:");

        tipoCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Profesor", "Administrativo" }));
        tipoCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("DNI:");

        buscarDniBtn.setText("Buscar");

        personasJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "DNI", "Nombre y apellido"
            }
        ));
        personasJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personasJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(personasJTable);

        jLabel3.setText("Nombre de contacto:");

        jLabel4.setText("Teléfono:");

        registrarBtn.setText("Registrar contacto");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Listado de contactos para el usuario seleccionado:");

        contactosJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº", "Nombre y apellido", "Teléfono", "Relación"
            }
        ));
        contactosJTable.setComponentPopupMenu(contactosPopUp);
        jScrollPane2.setViewportView(contactosJTable);

        jLabel6.setText("Relación:");

        relacionCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Padre/madre", "Esposo/Esposa", "Tío/Tia", "Primo/prima", "Abuelo/Abuela", "Amigo/amiga", "Hermano/hermana", "Otra" }));

        jLabel7.setText("Persona seleccionada:");

        personaSeleccionadaTxtField.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buscarDniTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarDniBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(personaSeleccionadaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefonoTxtField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreContactoTxtField)
                            .addComponent(relacionCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipoCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscarDniTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarDniBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(personaSeleccionadaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombreContactoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(telefonoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(relacionCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCBoxActionPerformed
        String tipo = this.tipoCBox.getSelectedItem().toString();
        if(tipo.equalsIgnoreCase("alumno")) {
            mostrarAlumnos();
        } else {
            if(tipo.equalsIgnoreCase("profesor")) {
                mostrarProfesores();
            } else {
                mostrarAdministrativos();
            }
        }
    }//GEN-LAST:event_tipoCBoxActionPerformed

    private void personasJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personasJTableMouseClicked
        int filaSeleccionada = this.personasJTable.getSelectedRow();
        String nombre = this.personasJTable.getValueAt(filaSeleccionada, 2).toString();
        
        this.personaSeleccionadaTxtField.setText(nombre);
        
        mostrarContactos();
        
    }//GEN-LAST:event_personasJTableMouseClicked

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        if(nombreContactoTxtField.getText().trim().equalsIgnoreCase("") || telefonoTxtField.getText().trim().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "¡Ningún campo puede estar vacio!", "Error: campos vacios.", JOptionPane.ERROR_MESSAGE);
        } else {
            
            String nombreContacto = this.nombreContactoTxtField.getText().trim();
            String telefono = this.telefonoTxtField.getText().trim();
            int personaId = Integer.valueOf(this.personasJTable.getValueAt(this.personasJTable.getSelectedRow(), 0).toString());
            String relacion = this.relacionCBox.getSelectedItem().toString();
            
            Contacto contacto = new Contacto();
            contacto.setNombre(nombreContacto);
            contacto.setTelefono(telefono);
            contacto.setRelacion(relacion);
            contacto.setPersonaId(personaId);
            contacto.save(contacto);
            
        }
    }//GEN-LAST:event_registrarBtnActionPerformed

    private void eliminarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarItemActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "¿Estás seguro que quieres eliminar este contacto?", "Información.", JOptionPane.YES_NO_OPTION);
        
        if(result == JOptionPane.YES_OPTION) {
            int filaSeleccionada = this.contactosJTable.getSelectedRow();
            
            if(filaSeleccionada == -1) {
                JOptionPane.showMessageDialog(this, "¡No se ha seleccionado ninguna fila!", "Error: ninguna fila seleccionada.", JOptionPane.ERROR_MESSAGE);
            } else {
                int contactoId = Integer.valueOf(this.contactosJTable.getValueAt(filaSeleccionada, 0).toString());
                new Contacto().delete(contactoId);
            }
            
            
            
        }
    }//GEN-LAST:event_eliminarItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Contactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Contactos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarDniBtn;
    private javax.swing.JTextField buscarDniTxtField;
    private javax.swing.JTable contactosJTable;
    private javax.swing.JPopupMenu contactosPopUp;
    private javax.swing.JMenuItem eliminarItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombreContactoTxtField;
    private javax.swing.JTextField personaSeleccionadaTxtField;
    private javax.swing.JTable personasJTable;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JComboBox<String> relacionCBox;
    private javax.swing.JTextField telefonoTxtField;
    private javax.swing.JComboBox<String> tipoCBox;
    // End of variables declaration//GEN-END:variables
}
